### ISSUE TITLE
init-script: configfs based usb configuration not working on Nexus 5X (bullhead).

### ISSUE THREAD

**Issue by RedL0tus** [mer-hybris/hybris-boot#139]
https://github.com/mer-hybris/hybris-boot/commit/ad27186290f5c65dea8c39c913bd739673ef078a will cause Nexus 5X to bootloop because the init script could not initialize USB gadget correctly.

Here is the init.log: https://pastebin.ubuntu.com/p/XXr6frWFn5/
Here is my kernel config: https://github.com/RedL0tus/android_kernel_lge_bullhead/blob/cm-14.1/arch/arm64/configs/lineageos_bullhead_defconfig

Maybe we should prefer using USB gadget mode than configfs for compatibility.

**Comment by krnlyng** [comment]
@RedL0tus I think we need a better way to determine whether the device needs configfs or android_usb.

If we make android_usb the default, devices with configfs will not work properly and vice versa.

**Comment by RedL0tus** [comment]
@krnlyng I think we don't have to check which mode will be used, just fallback to the other mode when one fails. Checkout #140. XD
